import type { ControllerProfile } from "./index";

export const genericHidButtons = [
  "BUTTON_0",
  "BUTTON_1",
  "BUTTON_2",
  "BUTTON_3",
  "BUTTON_4",
  "BUTTON_5",
  "BUTTON_6",
  "BUTTON_7",
  "BUTTON_8",
  "BUTTON_9",
  "BUTTON_10",
  "BUTTON_11",
  "BUTTON_12",
  "BUTTON_13",
  "BUTTON_14",
  "BUTTON_15",
  "DPAD_UP",
  "DPAD_DOWN",
  "DPAD_LEFT",
  "DPAD_RIGHT",
] as const;

export const genericHidProfile: ControllerProfile = {
  name: "generic-hid",
  buttons: genericHidButtons,
  triggers: ["BUTTON_6", "BUTTON_7"],
  aliases: {
    A: "BUTTON_0",
    B: "BUTTON_1",
    X: "BUTTON_2",
    Y: "BUTTON_3",
  },
  toUniversal: {
    BUTTON_0: "SOUTH",
    BUTTON_1: "EAST",
    BUTTON_2: "WEST",
    BUTTON_3: "NORTH",
    BUTTON_4: "LEFT_BUMPER",
    BUTTON_5: "RIGHT_BUMPER",
    BUTTON_6: "LEFT_TRIGGER",
    BUTTON_7: "RIGHT_TRIGGER",
    BUTTON_8: "SELECT",
    BUTTON_9: "START",
    BUTTON_10: "LEFT_STICK",
    BUTTON_11: "RIGHT_STICK",
    DPAD_UP: "DPAD_UP",
    DPAD_DOWN: "DPAD_DOWN",
    DPAD_LEFT: "DPAD_LEFT",
    DPAD_RIGHT: "DPAD_RIGHT",
  },
};
