import type { ControllerProfile } from "./index";

export const switchButtons = [
  "A",
  "B",
  "X",
  "Y",
  "L",
  "R",
  "ZL",
  "ZR",
  "MINUS",
  "PLUS",
  "HOME",
  "CAPTURE",
  "LS",
  "RS",
  "DPAD_UP",
  "DPAD_DOWN",
  "DPAD_LEFT",
  "DPAD_RIGHT",
] as const;

export const switchProfile: ControllerProfile = {
  name: "switch",
  buttons: switchButtons,
  triggers: ["ZL", "ZR"],
  features: {
    motion: true,
  },
  aliases: {},
  toUniversal: {
    B: "SOUTH",
    A: "EAST",
    Y: "WEST",
    X: "NORTH",
    L: "LEFT_BUMPER",
    R: "RIGHT_BUMPER",
    ZL: "LEFT_TRIGGER",
    ZR: "RIGHT_TRIGGER",
    MINUS: "SELECT",
    PLUS: "START",
    HOME: "HOME",
    CAPTURE: "CAPTURE",
    LS: "LEFT_STICK",
    RS: "RIGHT_STICK",
    DPAD_UP: "DPAD_UP",
    DPAD_DOWN: "DPAD_DOWN",
    DPAD_LEFT: "DPAD_LEFT",
    DPAD_RIGHT: "DPAD_RIGHT",
  },
};
